(global-set-key "\C-x\C-m" 'execute-extended-command)
(global-set-key "\C-c\C-m" 'execute-extended-command)
(global-set-key (kbd "<f12>") 'org-agenda)
(global-set-key (kbd "<f9> <f9>") 'bh/show-org-agenda)
(global-set-key (kbd "<f9> I") 'bh/punch-in)
(global-set-key (kbd "<f9> O") 'bh/punch-out)
(global-set-key (kbd "<f9> s") 'org-schedule)
(global-set-key (kbd "<f9> d") 'org-deadline)
(global-set-key (kbd "C-c c") 'org-capture)
(global-set-key (kbd "M-]") 'next-buffer)
(global-set-key (kbd "M-[") 'previous-buffer)
(global-set-key (kbd "C-x C-k") 'kill-current-buffer)
(global-set-key (kbd "C-x C-S-k") 'nuke-all-buffers)
(global-set-key (kbd "<f8> l") 'org-insert-last-stored-link)
(global-set-key (kbd "<f8> e") 'cs/estimate)
(global-set-key (kbd "C-c o")
		(lambda () (interactive) (find-file "~/ToDo/refile.org")))
(global-set-key (kbd "<f8> <f8>") 'cs/todays-page)
(global-set-key (kbd "C-c l") 'org-store-link)
(global-set-key (kbd "C-c C-l") 'org-insert-link)
(define-key org-mode-map "\C-cn" 'org-mactions-new-numbered-action)
